### ISSUE TITLE
Autoplay completly broken and unusable

### ISSUE THREAD

**Issue by Owizardo** [kangarko/AutoPlay#2]
Hi there,

I am using the latest version of Puncher Arena and Autoplay. I created a Puncher Arena and doing /p join ARENA_NAME works just fine. Using autoplay, I set it to world mode. 

I created a mini lobby in the same world where my Puncher arenas are located. Using the tool a set the lobby spawn point. When I join the Arena world, the autoplay starts correctly. When trying to select a class, I get the popup with the proper classes. When trying to click on a class my users are getting an error saying that there was a problem please see you administrator to look in the console. When the countdown finishes we get a message saying Game over... and count down restarts. No one is able to get to the actual arena even with OP.

Console I see errors saying "me.kangarko.puncher.nul . .w: Report / Player cache has not any arena!".

Full error:
```
Puncher 1.1.3 encountered a w
Running CraftBukkit 1.12.2-R0.1-SNAPSHOT and Java 1.8.0_151
Plugins: AsyncWorldEditInjector v2.3.0, dynmap v2.5-Dev201706100405, PlaceholderAPI v2.8.2, Boss v1.5.8, MMOItems v3.0.7, BannerBoard v1.9.8.2, The Multiverse-Core Plugin, ProtocolLib v4.3.0, ProdigyGadget v2.49.55, AsyncWorldEdit v3.4.11, GameAPI v1.1.1, HyperDrive-MC v1.3, iDisguise v5.6.4, AdvanceTab v1.3.6, PermissionsEx v1.23.4, Multiverse-Portals v2.5.0-b751, AutoPlay v1.0.7, HideAndSeek v3.0, Vault v1.6.1, MoneyMobs v3.532, TheLab v1.2, GUIPlus v1.21, BungeeNPC v1.20.6, DynamicStands v1.6.4, VirtualBag v4.1, ArcadeGames v1.2, SaneEconomy v0.13.1-SNAPSHOT, Citizens v2.0.22-SNAPSHOT (build 1498), CommandNPC v1.9.1, WorldEdit v6.1.8-SNAPSHOT;cd4729f, HyperDrive v3.8.4, Puncher v1.1.3, CoreArena v1.5.3, Essentials v2.0.1-b570, LeaderHeads v3.1.6, TitleManager v2.0.9, BannerBoard_LeaderHeads v1.0.7
----------------------------------------------------------------------------------------------

More Information: 
Player cache has not any arena!
w Report / Player cache has not any arena!
	 at me.kangarko.puncher.nul . .class.try(SourceFile:20)
	 at me.kangarko.puncher.nul . .byte.package(SourceFile:264)
	 at me.kangarko.puncher.nul . .Lpt9$Lpt1.try(SourceFile:102)
	 at me.kangarko.puncher.nul . .bL.try(SourceFile:262)
	 at me.kangarko.puncher.nul . .bO.onInvClick(SourceFile:61)
	 at sun.reflect.GeneratedMethodAccessor275.invoke(Unknown Source)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	 at java.lang.reflect.Method.invoke(Unknown Source)
	 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
----------------------------------------------------------------------------------------------

```

**Comment by Owizardo** [comment]
New update, after a reboot now this plugin has been randomly disconnecting me. After adding Load_After: "Multiverse-Core" in the config it then let me login. Now when trying to navigate into the menu I get console errors:
```

AutoPlay 1.0.7 encountered a AuX
Running CraftBukkit 1.12.2-R0.1-SNAPSHOT and Java 1.8.0_151
Plugins: AsyncWorldEditInjector v2.3.0, dynmap v2.5-Dev201706100405, PlaceholderAPI v2.8.2, MMOItems v3.0.7, RealDualWield v1.1.2, BannerBoard v1.9.8.2, NewItems v4.2.4, The Multiverse-Core Plugin, ProtocolLib v4.3.0, LibsDisguises v9.5.0, ProdigyGadget v2.49.55, AsyncWorldEdit v3.4.11, GameAPI v1.1.1, AdvanceTab v1.3.6, PermissionsEx v1.23.4, AutoPlay v1.0.7, HideAndSeek v3.0, Vault v1.6.1, MoneyMobs v3.532, TheLab v1.2, GUIPlus v1.21, DynamicStands v1.6.4, Essentials v2.0.1-b570, VirtualBag v4.1, ArcadeGames v1.2, SaneEconomy v0.13.1-SNAPSHOT, Citizens v2.0.22-SNAPSHOT (build 1498), CrazyAuctions v1.2.4, CommandNPC v1.9.1, TitleManager v2.0.9, WorldEdit v6.1.8-SNAPSHOT;cd4729f, LeaderHeads v3.1.6, Puncher v1.1.3, CoreArena v1.5.3
----------------------------------------------------------------------------------------------

More Information: 
Wait lobby not set
AuX Report / Wait lobby not set
	 at me.kangarko.autoplay.goto.nul. .Nul.nul(SourceFile:30)
	 at me.kangarko.autoplay.goto.nul. .C.lIIlIlllllllIIllllllIlIIIIIlllIIIlIlllllIlIIIllllIIllIIIIlIIIlIIlllllIIIIIIlllIllIIlIIllIllIIlllIlIllIllIlIlIIlIIIIllIlIIIIlIlIlIIllIlIlllIlIlIlIIlllIlIlllIlIIlIlIIIIlIIIIllllIIIllIIIlIIIlllllllllIIlIIllllIlIIIIllIIlllIIlllllllIIlIIlIlIlIIlIIIIlIlIlllIIIlIlIIllIllIllIIIlIllIIIIIIlllllIIlIIllllllIIllllIIlIIllllIIIIIlIlIIIlllIIlIlllIIlllIIIlllIIlIIIIIIlIlllIlIIIlIlIlIIlIllllIIllIIlllllIlIllIIIIllIIlIllIlIllIlIlIlIlIIllIIlIIllllIlIIllIIIIIIlIIIlIIIllIlIllIlIIIlIllllIlIIllIIIIIIIlIlIllIIllIIllllllIl(SourceFile:97)
	 at me.kangarko.autoplay.goto.nul. .Q.nul(SourceFile:62)
	 at me.kangarko.autoplay.goto.nul. .j.onToolClick(SourceFile:103)
	 at sun.reflect.GeneratedMethodAccessor194.invoke(Unknown Source)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	 at java.lang.reflect.Method.invoke(Unknown Source)
	 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
	 at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235)
	 at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202)
----------------------------------------------------------------------------------------------

```

**Comment by kangarko** [comment]
We´re on it, please mind a day´s delay before it gets solved.

**Comment by kangarko** [comment]
Hello, I am sorry for the delay.

Please test the latest AutoPlay and Puncher just released. I have solved the problem preventing you from selecting a class using AutoPlay's item. The other error should have been fixed as well, please notify me if this is not true. 

As a good practice, whenever an error happens I suggest a full server restart, in case you're using reload heavily.

**Comment by Owizardo** [comment]
Awesome thanks. So far the menu are working again. Im gonna rebuild my arenas and try again in a few mins.

**Comment by Owizardo** [comment]
Everything seemed okay but started using it again and seeing some new problems. Not sure if this is a bug but when I go into the world option I get this error in the console. 

Thought it was maybe because I didnt select an arena in the rotation. When I go into the arenas options and try to activate an arena I get an error saying that the arena is not in world. At the moment I have a world called Puncher where I keep all my arenas. Checked the autoplay setting but cant see anything I can change there.

So at the moment this is still not working for me. 

------------------------------------[ 24.02.2018 15:59:23 ]-----------------------------------
AutoPlay 1.0.8 encountered a AuX
Running CraftBukkit 1.12.2-R0.1-SNAPSHOT and Java 1.8.0_161
Plugins: AsyncWorldEditInjector v2.3.0, TopLite v1.3.1, dynmap v2.5-Dev201706100405, RedstoneProximitySensor v2.3.7, CrazyCrates v1.7.4.4, MoarBows v1.5.3.1, PlayerSettings v4.9.4, AgarthaLib vMysthoria, Boss v1.5.12, AdditionsAPI v1.2.7, MMOItems v3.0.8, BannerBoard v1.9.8.2, ActionBarAPI v1.5.3, The Multiverse-Core Plugin, ProtocolLib v4.3.0, LaunchPadPlus v2.0, LibsDisguises v9.5.0, ProdigyGadget v2.49.59, AsyncWorldEdit v3.4.11, GameAPI v1.1.1, AdvancedArmorstands v1.7.3, VanillaAdditions v1.2.7, Murder v10.1, PermissionsEx v1.23.4, CustomArrow vMysthoria, AutoPlay v1.0.8, HideAndSeek v3.0, Vault v1.6.1, MoneyMobs v3.532, TheLab v1.2, GUIPlus v1.21, Essentials v2.0.1-b570, BountyHunters v1.4.4, HeadDatabase v4.1.3, VirtualBag v4.1, ArcadeGames v1.2, SaneEconomy v0.13.1-SNAPSHOT, Citizens v2.0.22-SNAPSHOT (build 1504), UnrealShop v1.5.0-Beta, CrazyAuctions v1.2.4, CommandNPC v1.9.1, TitleManager v2.0.9, WorldEdit v6.1.8-SNAPSHOT;cd4729f, SurvivalGames v6.3, LeaderHeads v3.1.6, Puncher v1.1.6, CoreArena v1.5.4, MyPet v2.3.8
----------------------------------------------------------------------------------------------

More Information: 
Rotation is missing
AuX Report / Rotation is missing
	 at me.kangarko.autoplay.goto.nul. .Nul.AUX(SourceFile:20)
	 at me.kangarko.autoplay.goto.nul. .F.AUX(SourceFile:25)
	 at me.kangarko.autoplay.goto.nul. .z.LpT7(SourceFile:150)
	 at me.kangarko.autoplay.goto.nul. .z.lPt6(SourceFile:38)
	 at me.kangarko.autoplay.goto.nul. .z$LpT7$4.AUX(SourceFile:491)
	 at me.kangarko.autoplay.goto.nul. .finally.toString(SourceFile:169)
	 at java.util.Formatter$FormatSpecifier.printString(Unknown Source)
	 at java.util.Formatter$FormatSpecifier.print(Unknown Source)
	 at java.util.Formatter.format(Unknown Source)
	 at java.util.Formatter.format(Unknown Source)
	 at java.lang.String.format(Unknown Source)
	 at me.kangarko.autoplay.goto.nul. .interface.LpT7(SourceFile:86)
	 at me.kangarko.autoplay.goto.nul. .synchronized.registerField(SourceFile:116)
	 at me.kangarko.autoplay.goto.nul. .synchronized.registerFields(SourceFile:100)
	 at me.kangarko.autoplay.goto.nul. .synchronized.lambda$new$0(SourceFile:71)
	 at me.kangarko.autoplay.goto.nul. .lpt2.AUX(SourceFile:21)
	 at me.kangarko.autoplay.goto.nul. .synchronized.displayTo(SourceFile:141)
	 at me.kangarko.autoplay.goto.nul. .synchronized.displayTo(SourceFile:137)
	 at me.kangarko.autoplay.goto.nul. .z$1.AUX(SourceFile:60)
	 at me.kangarko.autoplay.goto.nul. .synchronized.onMenuClick(SourceFile:262)
	 at me.kangarko.autoplay.goto.nul. .switch.onInvClick(SourceFile:61)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	 at java.lang.reflect.Method.invoke(Unknown Source)
	 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
----------------------------------------------------------------------------------------------

**Comment by Owizardo** [comment]
Still the same issue with the latest version that just case out.

**Comment by kangarko** [comment]
I am on it, in the meanwhile please check that you selected your world in Rotation Menu -> Worlds

![a](https://i.imgur.com/v1uSAsg.png)

From reading your post I assume you already done it, please also try enabling rotation in that menu:
![b](https://i.imgur.com/ARmgx4r.png)

Let me know what menu closes itself with the error.

**Comment by Owizardo** [comment]
The issue is that I cannot access the worlds menu from autoplay. I get the error mentioned above when I click on it. Heres a short gif to how the issue: https://i.imgur.com/z2HG8iG.gif

`# !-----------------------------------------------------------------------------------------!
#                       Welcome to AutoPlay's main configuration
# !-----------------------------------------------------------------------------------------!
#
#   Here you can setup your minigames to be run automatically, which can be handy if:
#
#   a) Your entire server is a dedicated minigame server.
#   b) You want to have a dedicated world for games on your server.
#
#   Localization:
#   - To edit localization messages, create "localization" folder within AutoPlay's
#     folder and restart your server. A new file will appear that that you can edit directly.
#
# !-----------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------
# Select the autoplay mode. Set to "server" for automatic minigames on your entire server,
# "world" mode for minigames only on one of your worlds, or "disabled" to do nothing.
#
# HOW IT WORKS:
# AutoPlay will manage gameplay on your entire server or world. When the first player
# joins the server or world, the rotation will start automatically.
#
# It will not be possible to leave the arena without "autoplay.manager" permission
# or leaving the server or world.
#
# When players are not playing, they are only allowed to be in a wait-lobby location.
# Set up the location first with "/ag tools" command. Lobby for each arena will be skipped,
# if the plugin allows it.
#
# NB: You can exempt yourself from playing in the "/ag menu" menu.
#
# TIP: Place "[classes]" sign anywhere to open class selection menu.
# -------------------------------------------------------------------------------------------
Mode: world

# -------------------------------------------------------------------------------------------
# How should we choose the next arena the previous finishes? 
#
# a) INCREMENTAL - Go through all of loaded arenas and select the next one.
# b) RANDOM - Pick the next arena randomly from all loaded arenas.
# -------------------------------------------------------------------------------------------
Order: RANDOM

# -------------------------------------------------------------------------------------------
# Settings for server mode. This is the mode you want to use to
# dedicate YOUR ENTIRE SERVER to run minigames automatically.
# -------------------------------------------------------------------------------------------
Server_Mode:
  #
  # All settings for this mode can be managed in-game! Open "/ap menu".
  #

# -------------------------------------------------------------------------------------------
# Settings for world mode. This is the mode you want to use to
# dedicate ONE ENTIRE WORLD ON YOUR SERVER to run minigames automatically.
# -------------------------------------------------------------------------------------------
World_Mode: 
  #
  # Where players should be teleported when they quit? Type the world name.
  #
  Return_World: Hive

# -------------------------------------------------------------------------------------------
# Customize players message. Set to "default" to not modify, set to "none" or "" to hide.
# Variables: {server_name}, {player}, {world}, {arena} (played or scheduled arena)
#            
# PlaceholderAPI is supported!
# -------------------------------------------------------------------------------------------
Messages: 
  #
  # Join message - either for entire server or your world.
  #
  Join: "&8[&2+&8] &7{player}"
  #
  # Leave message - either for entire server or your world.
  #
  Quit: "&8[&4-&8] &7{player}"

# -------------------------------------------------------------------------------------------
# Should this plugin control players' inventories in server or world mode? See above.
# -------------------------------------------------------------------------------------------
Inventories: 
    #
    # If Server mode is enabled, players' will receive items below when they join the server.
    # In World mode they'll receive them when they come to the game world.
    #
    # In both cases, players cannot modify their inventory unless they have manager permission.
    #
    Enabled: true
    #
    # Specify what items player will get.
    #
    # Format:
    #  <position in inventory from 0 to 35>:
    #    Item: <bukkit material name> (see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html)
    #    # Should the item have the enchant glow?
    #    Glow: <true/false>
    #    # Custom name and lores
    #    Name:
    #      - <name>
    #      - <lores on each line [..]>
    #    # Invoke plugin's function. Currently: OPEN_CLASS_MENU and OPEN_MAIN_MENU
    #    Function: <function>
    #    # Commands to execute as console. Prepend with 'bungee' to send to the Bungeecords.
    #    Console_Commands:
    #      - <commands with / on each line [..]>
    #    # Commands to execute as the player (make sure they have right permissions!)
    #    Player_Commands:
    #      - <commands with / on each line [..]>
    #    # If you have Bungeecords, send player to another server?
    #    Send_To_Server: <server name>
    #    # Permission required to obtain this tool.
    #    Permission: <permission>
    #
    Items:
      #
      # Feel free to change, remove or edit anything below!
      #
      # This item will show information about your server.
      # 
      '0':
        Item: PAPER
        Glow: true
        Name: 
          - "&r&nInformation"
          - ""
          - "&7You can play arenas on"
          - "&7this server without the"
          - "&7need of manually joining."
      #
      # This item opens a menu where players can select their class.
      #
      '4': 
        Item: ENCHANTED_BOOK
        Name: 
          - "&r&nSelect Class"
          - ""
          - "&7Select your class"
          - "&7for the next arena."
        Function: OPEN_CLASS_MENU
      #
      # This item ONLY shows for managers (having autoplay.manager) permission.
      #
      '6': 
        Permission: "autoplay.manager"
        Item: ENDER_PEARL
        Name: 
          - "&r&nManager Menu"
          - ""
          - "&7Click to access"
          - "&7the manager menu."
        Function: OPEN_MAIN_MENU
      #
      # Move players back to another server on your network.
      #
      # BungeeCords required! (Othewise you can just change it.)
      #
      '8': 
        Item: WOOD_DOOR
        Name: 
          - "&r&nReturn to Hub"
          - ""
          - "&7Click to return"
          - "&7to the lobby server"
        Send_To_Server: hub
      #
      # This item teleports players back to spawn. Useful if you have World Mode enabled.
      #
      #'8': 
      #  Item: WOOD_DOOR
      #  Name: 
      #    - "&r&nBack to Spawn"
      #    - ""
      #    - "&7Click to return"
      #    - "&7to the server spawn"
      #  Player_Commands: 
      #    - spawn

# -------------------------------------------------------------------------------------------
# Scoreboard-related settings.
#
# TIP: You can edit the lines in the localization (see header above).
# -------------------------------------------------------------------------------------------
Scoreboard:
  #
  # Enable Scoreboard's functionality?
  #
  Enabled: true

# -------------------------------------------------------------------------------------------
# Configure various time durations.
# -------------------------------------------------------------------------------------------
Duration: 
  #
  # How long is the pause between one arena is finished till the next starts?
  #
  Wait_Lobby: 15 seconds
  #
  # The maximum delay for a game. This forces a minigame plugin to end after this time.
  #
  Arena: 5 minutes

# -------------------------------------------------------------------------------------------
# Settings related to when rotation is disabled (see the "Mode" key above) or paused
# (see "/autoplay menu" to pause it).
# -------------------------------------------------------------------------------------------
Security: 
  #
  # Kick all players except managers ("AutoPlay.manager" permission) when the rotation pauses?
  #
  Kick_On_Pause: false
  #
  # Only allow managers (having "AutoPlay.manager" permission) to join to the world
  # or server itself when the rotation is paused?
  #
  Deny_Join_On_Paused: false
  #
  # Same as above, but only effective when the "Mode" is "disabled" (see above).
  #
  Deny_Join_On_Disabled: false

# -------------------------------------------------------------------------------------------
# Open class selection menu by clicking a sign in the wait-lobby.
# -------------------------------------------------------------------------------------------
Class_Sign:
  #
  # Enable this feature?
  #
  Enabled: true
  #
  # Write each sign line on a new line. Maximum four lines.
  # When you change it, old signs will stop function!
  #
  Format: |-
          [classes]

# -------------------------------------------------------------------------------------------
# By default, we must know what world the arena is on, especially for World Mode.
# 
# Set to true to allow arenas to be added into rotation, even if they lack that information.
# -------------------------------------------------------------------------------------------
Allow_Unsafe_Arenas: false

# -------------------------------------------------------------------------------------------
# Advanced: If you have a multiworld plugin like Multiverse-Core, AND HAVE ISSUES,
#           write that plugin down (e.g. "Multiverse-Core") If all works, leave untouched.
#           We will wait for that plugin to load, and then load our system.
# -------------------------------------------------------------------------------------------
Load_After: ""

# -------------------------------------------------------------------------------------------
# Aliases are alternative command names which trigger the same command as the main command.
# Separate them with a comma, e.g: aliases: [autoplay, ag]
#
# * THE FIRST ALIAS IS THE MAIN LABEL, THAT MEANS AT LEAST ONE ALIAS MUST BE SPECIFIED. *
# -------------------------------------------------------------------------------------------
Command_Aliases: ["autoplay", "ap"]

# -------------------------------------------------------------------------------------------
# Change the language of the messages in this plugin, or completelly customize them.
#
# Currently: en [English]
# -------------------------------------------------------------------------------------------
Locale: en

# -------------------------------------------------------------------------------------------
# Almost each message begins with a prefix, customize it here or set to "" to disable.
# -------------------------------------------------------------------------------------------
Plugin_Prefix: "&3AutoPlay //&7"

# -------------------------------------------------------------------------------------------
# Print out some console information like "Changing phase to .." and similar?
# -------------------------------------------------------------------------------------------
Verbose: false

# -------------------------------------------------------------------------------------------
# Check and notify for newer versions of AutoPlay?
# -------------------------------------------------------------------------------------------
Notify_Updates: true

# -------------------------------------------------------------------------------------------
# Debugging allows you to understand the plugin. It will print more messages to the console.
# Specify sections to debug, or [*] to print all out, including some special messages.
#
# Available: rotation, teleport, MobArena, leak_detector
# -------------------------------------------------------------------------------------------
Debug: []

# Internal version check, please do not change!
Serialization_Number: ""

# Configuration version, do not change!
Version: 1

# That's it! You're done with the configuration :) Now, hop into the game and open "/ap menu"
# to enable the automatic rotation.`

**Comment by kangarko** [comment]
I am sorry I am having trouble getting down to the error cause. As you can see from the code, the rotation cannot be null, but either world, server, or dummy.

![a](https://i.imgur.com/5lblpuH.png)

Are you using PlugMan or /reload?

**Comment by Owizardo** [comment]
No im not using plugman or reload at the moment.

**Comment by Owizardo** [comment]
After clearing the plugin and its folder I seem to get a different error. This happens when I click on Worlds. This is the console error, there are no error logs generated by the application. 
```

16:04:44
AutoPlay // Error clicking in menu LpT7{}
WARN 02/27/2018 16:04:44
16:04:44
java.lang.NullPointerException
	at me.kangarko.autoplay.goto.nul. .R.Lpt5(SourceFile:150)
	at me.kangarko.autoplay.goto.nul. .A$lPt6.AUX(SourceFile:596)
	at me.kangarko.autoplay.goto.nul. .A$lPt6.AUX(SourceFile:577)
	at me.kangarko.autoplay.goto.nul. .f.getItemAt(SourceFile:120)
	at me.kangarko.autoplay.goto.nul. .finally.displayTo(SourceFile:153)
	at me.kangarko.autoplay.goto.nul. .finally.displayTo(SourceFile:137)
	at me.kangarko.autoplay.goto.nul. .A$LpT7$1.AUX(SourceFile:389)
	at me.kangarko.autoplay.goto.nul. .finally.onMenuClick(SourceFile:262)
	at me.kangarko.autoplay.goto.nul. .final.onInvClick(SourceFile:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
	at java.lang.Thread.run(Unkno
```wn Source)

**Comment by Owizardo** [comment]
Ok I finally fixed it. I had to delete an unfinished CoreArena arena. Now I can select the worlds just fine. Im gonna keep testing to see if its fully working.

**Comment by Owizardo** [comment]
We can close this, everything seems good now.

**Comment by kangarko** [comment]
Interesting. No I am not going to close this because I think there is an error on my side that needs to be fixed. We'll be investigating this asap.

In what stage the unfinished arena was? (You can read what was set and what not in the sidebar while in the edit mode).

**Comment by kangarko** [comment]
Okay I resolved this problem. It lied in that the arena lacked a world so the Worlds menu could not compare it to it and crashed.

**Comment by kangarko** [comment]
Alright I had split the tools. After some testing it should work fine!

![a](https://i.imgur.com/m07A8am.png)
