### ISSUE TITLE
Bug? - Puncher / Autoplay - Not asking to select team during class selection

### ISSUE THREAD

**Issue by Owizardo** [kangarko/AutoPlay#4]
Hi not sure if this is a bug, when joining the Puncher game world I get the items to select the class. Right clicking the book gives you a menu with the list of available classes. When selecting a class the menu closes and you get the classes items as expected. 

Everything seems to work great however I am expecting to be asked for a team to choose from at some point but never do. Instead Autoplay warps us to the arena and auto selects the team for you. Is this a normal behavior?

To be sure I cleared my Puncher and Autoplay folders and restarted from scratch but still get the same behavior.

**Comment by kangarko** [comment]
Unfortunatelly there is no native team support at the moment. Would you like the team menu to be opened right after the class menu or as a separate icon?

You can place signs to select teams: ![a](https://i.imgur.com/8rIgvPN.png)

**Comment by Owizardo** [comment]
First off thank you so much for all the support and quick answers I hope others notice all the hard work your putting in. Keep it up! :) 

I think it would be good to have the popup right after you select your class, I think this way would make the most sense for me. Its more for beginers to not forget to select their team and avoid some confusion to know what team your on. 

Personally, I would prefer having the option of teams or free for all. But I think this would be a seperate request :P.

**Comment by kangarko** [comment]
I have added support for [team] signs directly to Puncher that will open up the menu. I also added a separate icon to select teams. Due to extensive code changes required I am not planning to auto-open team menu after classes menu, surprisingly that would be most difficult.
