### ISSUE TITLE
Autoplay Rotation Error

### ISSUE THREAD

**Issue by LucidusMC** [kangarko/AutoPlay#8]
Paper 1.13.2
Autplay 1.2.15
CoreArena 1.8.3
Puncher 1.4.2
Server Mode

I have CoreArena and Puncher setup (working as far as I know...) and I go into the autoplay menu and click Rotation Menu and then I get this console error and I have also included the autoplay error log.

Console Error:
https://pastebin.com/EUYMvFgP

Error Log:
https://pastebin.com/4qRM3M2g

Thanks!

Edit: I have included all my settings files and plugins below. (removed mysql settings for security)

12.02 01:43:38 [Server] INFO Plugins (8): AsyncWorldEdit, AutoPlay, CoreArena, GameAPI, Puncher, ReWorld, VoidGenerator, WorldEdit

[settings.zip](https://github.com/kangarko/AutoPlay/files/2854405/settings.zip)

**Comment by kangarko** [comment]
Thanks. Seems your arenas contain same names across CoreArena or Puncher. I will fix the problem in the next version.

**Comment by LucidusMC** [comment]
Oh, hah, was like "I wonder if naming them the same is the issue, nahhh".  I will test it this evening. Thanks!

**Comment by LucidusMC** [comment]
Unfortunately, I updated all three plugins, removed and recreated the arenas, made new classes, took new snapshots (I found the schematics folder in WorldEdit, duh, where your snapshots are kept) made sure the new snapshots had unique names, when back to my lobby world and went and clicked Rotation Menu and got the same looking console errors.  I will post them below just in case they are different.  Thanks for your help, can't wait to get this working!

Console Error:
https://pastebin.com/XgL3Lht4

Error.log:
https://pastebin.com/HMJYgCUj

**Comment by kangarko** [comment]
Hey, to put an arena into the rotation, you must manually add it in the rotation menu.

For the errors, have you reloaded during your setup? Please test the next version. Please don't use /ap reload or /rl nor PlugMan. I am investigating this problem and it seems to be related to reloading.

**Comment by LucidusMC** [comment]
@kangarko 

ok, how do I manually add it? Via GUI? Maybe this is the part I'm missing, I have activated the area in each plugin, but I can't use AP rotation menu because it gives me an error in the GUI.

I don't use reload or reload plugins (at least not that I remember, I may have in desperation in one of my iterations, heh), I always try to stop and start my servers.

-Kris

**Comment by LucidusMC** [comment]
@LucidusMC 

Still same issues, followed all your directions.

**Comment by kangarko** [comment]
Hi, I am on it, apology for the delay.

**Comment by kangarko** [comment]
Hey, so I went through everything you provided and tested on my server. I have added additional safety checks and the next release should bring clarity and a solution to the problem. Appreciated your patience <3

**Comment by kangarko** [comment]
Fixed in PM
